# permissions for end users to edit websites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: website-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-operator
    app.kubernetes.io/part-of: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: website-editor-role
rules:
- apiGroups:
  - web.dewey-typical.github.io
  resources:
  - websites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.dewey-typical.github.io
  resources:
  - websites/status
  verbs:
  - get
