apiVersion: web.dewey-typical.github.io/v1alpha1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: website
    app.kubernetes.io/instance: website-sample
    app.kubernetes.io/part-of: nginx-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nginx-operator
  name: website-sample
spec:
  # TODO(user): Add fields here
  title: my-sample-website
  content: |
    <html>
      <body>
        <h1>Hello World</h1>
      </body>
    </html>
